### ISSUE TITLE
hi, 请问

### ISSUE THREAD

**Issue by lzl124631x** [jinlong/jinlong.github.com#2]
对你的博客的实现很感兴趣, 但是发现这个repo中只有生成后的文件. 我看使用了hexo以及一些vendor库, 你的博客实现不方便公开么?

**Comment by jinlong** [comment]
哦，这个没什么特别的，就是按hexo的教程搭建的，然后用了Next主题。

可以参考下面这篇文章：
[hexo你的博客](http://ibruce.info/2013/11/22/hexo-your-blog/)

我后来觉得直接用github 的 issues 作博客也挺省事的。

**Comment by lzl124631x** [comment]
好的, 我目前在用jekyll, 一直知道hexo可以做到更好的效果(jekyll好多要自己实现), 不过想试试jekyll能做成啥样, 做腻了再转hexo. 看了你的博客感觉效果很酷炫, 忍不住要试试hexo了.

感谢.
