### ISSUE TITLE
ofo国际化部门求前端

### ISSUE THREAD

**Issue by jinlong** [jinlong/jinlong.github.com#3]
ofo国际化部门求前端，期待优秀的你

前端 HTML、CSS、JavaScript 基础扎实，熟悉 vue.js 全家桶 或 React.js 全家桶

1、计算机相关专业,本科以上学历，3年以上Web前端开发经验。 
2、喜欢Web前端技术，对于HTML、CSS、JavaScript有较为深入的研究；。 
3、熟悉W3C规范，能熟练编写具有良好风格规范的代码
4、熟悉HTML5、CSS3和Hybrid等相关技术； 
5、熟悉react相关技术优先考虑； 
6、良好的团队协作意识和积极的工作态度。

邮箱：zhangjinlong-rj@ofo.com

**Comment by jinlong** [comment]
地点：北京

**Comment by jinlong** [comment]
地点：北京

**Comment by JerrodNoliita** [comment]
请问，你写的浏览器前端优化这篇文章中的画图软件叫什么
